# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
dist: trusty

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "10"

# https://docs.travis-ci.com/user/caching/
cache:
  yarn: true

notifications:
  email: false

# http://docs.travis-ci.com/user/deployment/
#after_success:
#  - if [ "$TRAVIS_BRANCH" == "dev" ]; then yarn build:prod; fi
#  - if [ "$TRAVIS_BRANCH" == "edge" ]; then yarn build:prod; fi
#  - if [ "$TRAVIS_BRANCH" == "staging" ]; then yarn build:prod; fi
#  - if [ "$TRAVIS_BRANCH" == "prod" ]; then yarn build:prod || { echo 'contents of npm-debug.log:' && cat /home/travis/build/wireapp/wire-webapp/npm-debug.log && exit 1; } fi

stages:
  - deploy

jobs:
  include:
    - stage: deploy
      if: tag =~ .*-staging.*
      deploy:
      - provider: script
        script: "echo 'deployed!'"
        condition: tag =~ .*-staging.*

# after_deploy:
#   - |
#     if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${TRAVIS_EVENT_TYPE}" == "push" ]; then
#         echo "deployment done"
#     fi
#
# after_failure:
#   - |
#     if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
#       if [[ "${TRAVIS_BRANCH}" =~ ^(dev|prod|staging|master)$ ]]; then
#         echo "failed to deploy"
#       fi
#     fi
